version: "3.8"

# 默认日志配置
x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "5"

# php 相关环境配置
x-php: &default-php
  build: ./dockerfile/php
  #不想编译的可以直接使用镜像
  # image: ghcr.io/meowpay/dujiaoka:v2024_01_25
  volumes:
    - ./conf.d/:/etc/nginx/conf.d/
    - ./dujiaoka/:/var/www/dujiaoka/
  depends_on:
    - mysql
    - redis
  logging: *default-logging

# 服务
services:
  # 代理服务器
  nginx:
    build: ./dockerfile/nginx
    # container_name: DujiaokaNginx
    volumes:
      - ./conf.d/:/etc/nginx/conf.d/
      - ./dujiaoka/:/var/www/dujiaoka/
    ports:
      - 80:80
      # 不需要https注释掉下行
      - 443:443
    restart: always
    command: [nginx, "-g", "daemon off;"]
    logging: *default-logging
    depends_on:
      - mysql
      - redis
  # 数据库
  mysql:
    image: mysql:latest
    # container_name: DujiaokaMysql
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-pw
      - MYSQL_DATABASE=dujiaoka
    expose:
      - 3306
    volumes:
      - ./data/mysql:/var/lib/mysql
    restart: always
    logging: *default-logging
  # PHP环境
  php:
    <<: *default-php
    restart: always

  # Redis
  redis:
    # container_name: Redis
    image: redis:latest
    volumes:
      - ./data/redis_data:/data
    command: redis-server --save 60 1 --loglevel warning
    logging: *default-logging
    expose:
      - 6379
    restart: always
  # 任务队列
  php-queue:
    command: php /var/www/dujiaoka/artisan queue:work
    <<: *default-php
    #不想编译的可以直接使用镜像
    # image: ghcr.io/meowpay/dujiaoka:v2024_01_25
    # container_name: DujiaokaPhpQueue
    restart: always

  # 安装依赖
  php-compose:
    <<: *default-php
    # container_name: DujiaokaCompose
    command: /bin/bash -c "cd /var/www/dujiaoka;/usr/local/bin/composer install --ignore-platform-reqs --no-scripts"
